spring:
  application:
    name: server
  config:
    import:
      - datasource.yml
      - optional:file:.env[.properties]
  profiles:
    active: local
    group:
      local: local
      dev: dev
      test: test
      prod: prod


custom:
  oauth:
    clientId: ${GITHUB_CLIENT_ID}
    secretKey: ${GITHUB_SECRET_KEY}
