spring:
  application:
    name: server
  config:
    import:
      - datasource.yml
      - optional:file:.env[.properties]
      - oauth.yml
  profiles:
    active: local
    group:
      local: local
      dev: dev
      test: test
      prod: prod

